language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
services:
  - xvfb
before_install:
  - pip install -U pip
  - export BOTO_CONFIG=/dev/null
install:
  - make requirements
script:
  - make selfcheck
  - make quality
  - make test
  - make validate_translations
notifications:
  email: false
addons:
  firefox: 36.0
